// <auto-generated />
using EpicQuestData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EpicQuestData.Migrations
{
    [DbContext(typeof(EpicQuestContext))]
    partial class EpicQuestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EpicQuestEntities.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int?>("QuestId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("EpicQuestEntities.Quest", b =>
                {
                    b.HasOne("EpicQuestEntities.Quest")
                        .WithMany("ChainQuests")
                        .HasForeignKey("QuestId");
                });
#pragma warning restore 612, 618
        }
    }
}
